# Generated by Django 4.2.6 on 2023-10-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_story_chapter_count_alter_story_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='editor',
        ),
    ]
