# Generated by Django 4.2.6 on 2023-10-11 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stories', '0003_remove_story_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='slug',
        ),
    ]
