# Generated by Django 4.2.6 on 2023-10-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stories', '0004_remove_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
