# Generated by Django 4.2.6 on 2023-10-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_title',
        ),
    ]
