# Generated by Django 4.2.6 on 2023-10-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_remove_chapter_chapter_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
    ]
