# Generated by Django 4.2.6 on 2023-10-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stories', '0007_rename_author_name_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
