# Generated by Django 4.2.6 on 2023-10-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stories', '0009_alter_author_name_alter_chapter_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
