# Generated by Django 4.2.6 on 2023-10-11 14:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stories', '0010_alter_author_name_alter_chapter_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
