# Generated by Django 4.2.6 on 2023-10-13 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stories', '0011_alter_story_cover_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='author_id',
            new_name='author',
        ),
    ]
