# Generated by Django 4.2.6 on 2023-10-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stories', '0012_rename_author_id_story_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genres',
            field=models.ManyToManyField(through='stories.StoryGenre', to='stories.genre'),
        ),
    ]
