# Generated by Django 4.2.6 on 2023-10-13 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stories', '0014_remove_story_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storygenre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='storygenre',
            old_name='story_id',
            new_name='story',
        ),
    ]
