# Generated by Django 4.2.6 on 2023-10-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stories', '0016_remove_readingstats_reading_stats_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('dropped', 'Dropped')],
                                   default='ongoing', max_length=9),
        ),
    ]
