# Generated by Django 4.2.6 on 2023-12-18 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stories', '0018_rename_publish_date_chapter_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_number',
            new_name='chapter_name',
        ),
    ]
