# Generated by Django 4.2.6 on 2023-12-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_rename_chapter_number_chapter_chapter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_name',
        ),
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
