# Generated by Django 4.2.6 on 2024-01-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
