# Generated by Django 4.2.6 on 2024-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0024_alter_readingstats_date_alter_story_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number_chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingstats',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='ongoing', max_length=9),
        ),
    ]
