# Generated by Django 4.2.6 on 2024-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0025_alter_chapter_number_chapter_alter_readingstats_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genres',
            field=models.ManyToManyField(through='stories.StoryGenre', to='stories.genre'),
        ),
    ]
