# Generated by Django 4.2.6 on 2024-03-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0027_story_latest_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number_chapter',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
