# Generated by Django 4.2.6 on 2024-03-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0028_alter_chapter_number_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingstats',
            name='date',
            field=models.DateField(),
        ),
    ]
