# Generated by Django 4.2.6 on 2024-03-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0029_alter_readingstats_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
