# Generated by Django 4.2.6 on 2024-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0030_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255),
        ),
    ]
