# Generated by Django 4.2.6 on 2024-03-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0030_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number_chapter',
            field=models.IntegerField(db_index=True, default=-1),
            preserve_default=False,
        ),
    ]
