name: Deploy to EC2

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: EC2
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.DEPLOY_DIR }}

      - name: Run backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            if ! lsof -i:8000; then
              cd ${{ secrets.DEPLOY_DIR }}
              source venv/bin/activate
              screen -dm bash -c "python manage.py runserver 0.0.0.0:8000"
            fi

  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Django Server
        run: |
          python manage.py runserver &
          echo $! > django_pid.txt
          sleep 5
        env:
          DB_ENGINE: 'django.db.backends.sqlite3'
          DB_NAME: 'data.sqlite3'

      - name: Health Check
        run: |
          curl http://localhost:8000/common/health/

      - name: Stop Django Server
        if: always()
        run: |
          kill $(cat django_pid.txt)