name: Deploy to EC2

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: EC2
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.DEPLOY_DIR }}
  health_check:
    runs-on: ubuntu-latest
    env:
      DB_ENGINE: 'django.db.backends.sqlite3'
      DB_NAME: 'data.sqlite3'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Django Server
        run: |
          python manage.py runserver &
          echo $! > django_pid.txt
          sleep 10

      - name: Health Check
        run: |
          curl http://localhost:8000/common/health/

      - name: Stop Django Server
        if: always()
        run: |
          kill $(cat django_pid.txt)